---
title: "Projet statapp"
author: "Lyna EL KAMEL"
date: "2025-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("clubSandwich")
```


```{r cars}
library(haven)     # For reading Stata files
library(glmnet)    # For Lasso and Ridge regression
library(plotmo)    # For plots using Lasso and Ridge
library(dplyr)     # For data manipulation
library(estimatr)
library(gtsummary) #Pour faire de beaux tableaux
library(sandwich) #Pour les cluster
library(clubSandwich)
library("rlang")
library(lmtest)  # Charge le package

```

```{r}
# Accès aux données
data_path = 'C:/Users/lynae/OneDrive - GENES/Bureau/ENSAE/statapp/Base de donnée/Main Analysis and Paper/Analysis data' 
data <- read_dta(paste0(data_path, "/bt_analysis_final.dta"))
```



```{r}
#Je charge mes fonctions 
source("my_functions.R")
```

# Rreproduction des principaux tableaux de l'article
## Reproduction du tableau 2
```{r}
#Je fais ma régression  pour Gender attitude 
run_lm_robust(filter(data, !is.na(E_Steam_id) & attrition_el == 0), "E_Sgender_index2", c("bl_gender_flag", "el_gender_flag"))

```


```{r}
#Régression pour Behavior index
run_lm_robust(filter(data, !is.na(E_Steam_id) & attrition_el == 0), "E_Sbehavior_index2", c("el_behavior_common_flag","bl_behavior_common_flag"))
```

```{r}
run_lm_robust(filter(data, !is.na(E_Steam_id) & attrition_el == 0 & B_Sgirl==1), "E_Saspiration_index2", c("bl_aspiration_flag", "el_aspiration_flag"))
```


## Analyse de l'hétérogénéité (effet du genre)
Voir code stata L500
```{r}
#Le résultat de l'interaction n'est pas significatif pour Gender Attitude
run_lm_robust_girls(filter(data, !is.na(E_Steam_id) & attrition_el == 0), "E_Sgender_index2", c("el_gender_flag"))
```

```{r}
run_lm_robust(filter(data, !is.na(E_Steam_id) & attrition_el == 0), "E_Sbehavior_index2", c("el_behavior_common_flag","bl_behavior_common_flag"))
```

## Analyse de l'hétérogénéité (effet du genre et wealth proxies)
```{r}

```




