****************************************************************************
*
*	 Project: Breakthrough (BT)
*
*	 Purpose: Codifying other variables
*
****************************************************************************


* ===================================================================== *
* -----------------     	  DROPOUTS		          ----------------- *
* ===================================================================== *


	gen school_dropout_10=0 if !mi(school_dropout)
	label var school_dropout_10 "Why did you stop going to school? - Student fell sick"
	
	gen school_dropout_11=0 if !mi(school_dropout)
	label var school_dropout_11 "Why did you stop going to school? - Student got married"
	
	gen school_dropout_12=0 if !mi(school_dropout)
	label var school_dropout_12 "Why did you stop going to school? - School is far away"
	
	gen school_dropout_13=0 if !mi(school_dropout)
	label var school_dropout_13 "Why did you stop going to school? - School cancelled the registration"
	
    gen school_dropout_14=0 if !mi(school_dropout)
	label var school_dropout_14 "Why did you stop going to school?- Student failed"
	
	gen school_dropout_15=0 if !mi(school_dropout)
	label var school_dropout_15 "Why did you stop going to school?- Could not concentrate on studies"
	

	label values school_dropout_10 school_dropout_11 school_dropout_12 school_dropout_13 school_dropout_14 school_dropout_15 dropout
	order school_dropout_10 school_dropout_11 school_dropout_12 school_dropout_13 school_dropout_14 school_dropout_15, after(school_dropout_8)

	
	**replacing
	replace school_dropout_15=1 if school_dropout_reason_other=="Padai me dimag nahi lagta tha lekin school jana pasand h" 
	replace school_dropout_15=1 if school_dropout_reason_other=="Weak mind"
	replace school_dropout_6=1 if school_dropout_reason_other=="School me teacher ke sath ldai ho gyi thi"
    replace school_dropout_1=1 if school_dropout_reason_other=="Jee ni karta"	
	replace school_dropout_8=1 if school_dropout_reason_other=="Mother expired"
    replace school_dropout_8=1 if school_dropout_reason_other=="Father bimar ho gye the isliye"
    replace school_dropout_8=1 if school_dropout_reason_other=="Mammy bimar ho gyi thi isiliye school jana chhod diya"
    replace school_dropout_14=1 if school_dropout_reason_other=="9th class me fail hone kkarn."
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail ho gya tha"
	replace school_dropout_10=1 if school_dropout_reason_other=="Dora  ata ha es lya school l Jana chodya"
	replace school_dropout_13=1 if school_dropout_reason_other=="Bacha guam ho gya tha 3 month school me name cute gya tha isliya"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimari ke karn"
	replace school_dropout_12=1 if school_dropout_reason_other=="Dur tha"
	replace school_dropout_13=1 if school_dropout_reason_other=="Ghar chale gaye school say name cut gaya"
	replace school_dropout_14=1 if school_dropout_reason_other=="fail in class9th"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail hone k karen"
	replace school_dropout_13=1 if school_dropout_reason_other=="Buhkar ho gya tha school se jedya chutti le li thi isliye name kat gya"
	replace school_dropout_13=1 if school_dropout_reason_other=="School walo n nam kat diya"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimari ke karn chod diva tha"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimag nahi chalta tha"
	replace school_dropout_13=1 if school_dropout_reason_other=="naam Kat gaya school se"
	replace school_dropout_13=1 if school_dropout_reason_other=="Kai chutti hone k karn name cutt kardiya school walo n"
	replace school_dropout_14=1 if school_dropout_reason_other=="9th class me fail ho gya tha"
    replace school_dropout_10=1 if school_dropout_reason_other=="Eye problem"
	replace school_dropout_13=1 if school_dropout_reason_other=="School se naam kat diya gya"
	replace school_dropout_13=1 if school_dropout_reason_other=="Master na school sa name khat diya"
	replace school_dropout_10=1 if school_dropout_reason_other=="Student ki tabiyat thik nhi rhti thi bimari ke karn"
	replace school_dropout_10=1 if school_dropout_reason_other=="Tabiyat kharab rahti thi ."
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail ho gya tha isliye"
	replace school_dropout_14=1 if school_dropout_reason_other=="failed in 9th class"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimag Nahi Chala"
	replace school_dropout_13=1 if school_dropout_reason_other=="School se chutti li isliye name kaat diya"
	replace school_dropout_13=1 if school_dropout_reason_other=="Naam kat diya tha"
	replace school_dropout_13=1 if school_dropout_reason_other=="Haridwar jane pr school se naam kt gya tha jiski vajh se bache ne school jaana chod diyaa"
	replace school_dropout_15=1 if school_dropout_reason_other=="Mind nhi chla study m"
	replace school_dropout_13=1 if school_dropout_reason_other=="3 4 din lagatar chutti krne par teacher ne dobara class me nhi baithne diya"
	replace school_dropout_10=1 if school_dropout_reason_other=="Tabiyat kharab hone k karan"
	replace school_dropout_13=1 if school_dropout_reason_other=="Naam kaat diya gaya tha"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail hone ki wajah se"
	replace school_dropout_13=1 if school_dropout_reason_other=="School se naam kaat diya gaya tha"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimari k karan"
	replace school_dropout_13=1 if school_dropout_reason_other=="Bache ka name cute gya tha fir maan ni kiya  school me jaane ka"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar ho gya tha isliye"
	replace school_dropout_13=1 if school_dropout_reason_other=="chool walo n name cut kr diya"
	replace school_dropout_13=1 if school_dropout_reason_other=="Bache ka name cute gya tha dobra ni likhvana gya"
	replace school_dropout_15=1 if school_dropout_reason_other=="Short mind"
	replace school_dropout_13=1 if school_dropout_reason_other=="School walo na nam kaat diya"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimak nhi chlta"
	replace school_dropout_10=1 if school_dropout_reason_other=="Student bimaar ho gayatha."
	replace school_dropout_10=1 if school_dropout_reason_other=="Bike pe accident ho gya tha"
	replace school_dropout_10=1 if school_dropout_reason_other=="bimari ke karn"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar ho gya tha isliye nhi ja paya to nam kat diya"
	replace school_dropout_15=1 if school_dropout_reason_other=="Pdayi me mind nhi chla isliye"
	replace school_dropout_14=1 if school_dropout_reason_other=="9th class m fail hone kkarn"
	replace school_dropout_13=1 if school_dropout_reason_other=="Bacha jyda bimar hone ke karn name cute gya tha dubra ni likha gya"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimari se lambi chhuti k karan"
	replace school_dropout_15=1 if school_dropout_reason_other=="Padhne mein dimaag nahi chale tha"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimag nhi chlta"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimag nhi chalta"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimag nahi chala"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar hona ho gya tha nam kat diya phir likha nhai"
	replace school_dropout_15=1 if school_dropout_reason_other=="Study do not understand"
	replace school_dropout_15=1 if school_dropout_reason_other=="Pdai me dimakh ni chlta"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimak nhi chla isliye"
	replace school_dropout_10=1 if school_dropout_reason_other=="Haath tutne ke kaaran naam kaat diya gaya"
	replace school_dropout_14=1 if school_dropout_reason_other=="Compartment aagyi thi"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fall"
	replace school_dropout_11=1 if school_dropout_reason_other=="Saadi ho gai thi"
	replace school_dropout_12=1 if school_dropout_reason_other=="Gain we school door tha"
	replace school_dropout_12=1 if school_dropout_reason_other=="School jayada dur tha"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar hone k karan"
	replace school_dropout_15=1 if school_dropout_reason_other=="Yaad krne main problem hoti h"
	replace school_dropout_10=1 if school_dropout_reason_other=="Illness"
	replace school_dropout_15=1 if school_dropout_reason_other=="Dimag nhi chlta tha padai me"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimare ke karan"
	replace school_dropout_10=1 if school_dropout_reason_other=="Because of illness"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimaar thi isliye"
	replace school_dropout_11=1 if school_dropout_reason_other=="Saadi ho gai"
	replace school_dropout_11=1 if school_dropout_reason_other=="Marriage Ho gaye es liye"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bhimar thi me"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimari k karn"
	replace school_dropout_11=1 if school_dropout_reason_other=="Saadi ho gai h"
    replace school_dropout_10=1 if school_dropout_reason_other=="Bemari kay karen"
	replace school_dropout_11=1 if school_dropout_reason_other=="Sadi k karan"	
	replace school_dropout_14=1 if school_dropout_reason_other=="Student exam me fail ho gyatha isliye"
	replace school_dropout_10=1 if school_dropout_reason_other=="Lambe time  se Bimar h"
	replace school_dropout_14=1 if school_dropout_reason_other=="Resion fell"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail Ho gae"
	replace school_dropout_10=1 if school_dropout_reason_other=="Tabiyat khrab rhti thi"
	replace school_dropout_14=1 if school_dropout_reason_other=="9th me fail hone ke kaaran."
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail hone k karan"
	replace school_dropout_11=1 if school_dropout_reason_other=="Shadi ho gyi"
	replace school_dropout_10=1 if school_dropout_reason_other=="Apni bimari k karan chhod diya tha"
	replace school_dropout_13=1 if school_dropout_reason_other=="ladki Bimar thi or madam ny nm kat diya"
	replace school_dropout_12=1 if school_dropout_reason_other=="School door ke karan chod diya"
	replace school_dropout_10=1 if school_dropout_reason_other=="Student bimar rehti thi"
	replace school_dropout_10=1 if school_dropout_reason_other=="Child  ki health stuition thick nahi h"
	replace school_dropout_10=1 if school_dropout_reason_other=="Student ki health thick nahi thi"
	replace school_dropout_15=1 if school_dropout_reason_other=="Weak in study"
	replace school_dropout_15=1 if school_dropout_reason_other=="Mind nhi chla"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar ke karan padaai chod di"
	replace school_dropout_15=1 if school_dropout_reason_other=="Padhne ka mann nhi kar rha tha"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar rhti thi"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fel  hone ke karn"
	replace school_dropout_10=1 if school_dropout_reason_other=="Tabiyat tik nhi rhti hai"
    replace school_dropout_14=1 if school_dropout_reason_other=="Because of fail in 9th class."
	replace school_dropout_11=1 if school_dropout_reason_other=="Sadi kar di gayi h"
    replace school_dropout_14=1 if school_dropout_reason_other=="Fale ho ghi the"
	replace school_dropout_11=1 if school_dropout_reason_other=="Sadi  hone vali  h"
	replace school_dropout_14=1 if school_dropout_reason_other=="2 subjects me re aane ki wajah se"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fail ho gai thi"
	replace school_dropout_11=1 if school_dropout_reason_other=="Sadi"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimaar"
	replace school_dropout_10=1 if school_dropout_reason_other=="tudent bimar jyda rehta tha isliye"
	replace school_dropout_14=1 if school_dropout_reason_other=="Fale ho ghi the 9th me"
	replace school_dropout_11=1 if school_dropout_reason_other=="She is marid"
	replace school_dropout_11=1 if school_dropout_reason_other=="Marriage"
	replace school_dropout_11=1 if school_dropout_reason_other=="Shadi ho gyi thi"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bamiri k karn"
	replace school_dropout_11=1 if school_dropout_reason_other=="Sadi hone k karan"
	replace school_dropout_10=1 if school_dropout_reason_other=="Tabiyt kharb Ho janeke krna"
	replace school_dropout_15=1 if school_dropout_reason_other=="Padhai me kamjor hone ki wajah se"
	replace school_dropout_10=1 if school_dropout_reason_other=="Sar main dard tha"
	replace school_dropout_10=1 if school_dropout_reason_other=="Àankhe me problem"
	replace school_dropout_10=1 if school_dropout_reason_other=="Bimar hone ki wahah se"
	replace school_dropout_10=1 if school_dropout_reason_other=="Vimar ho gaye"
	replace school_dropout_11=1 if school_dropout_reason_other=="Mared"
	
	
	

* ===================================================================== *
* -----------------     	 FEMALE FOETICIDE		  ----------------- *
* ===================================================================== *
	


	//br child_id female_foeticide* if female_foeticide_reason_other!=""
	
	gen female_foeticide_reason_11=0 if !mi(female_foeticide)
	label var female_foeticide_reason_11 "Main reason for female foeticide and infanticide - girls cannot carry forward the family lineage"
	
    gen female_foeticide_reason_12=0 if !mi(female_foeticide)
	label var female_foeticide_reason_12 "Main reason for female foeticide and infanticide - girls are considered a curse"	

	label values female_foeticide_reason_11 female_foeticide_reason_12 female_foeticide_reason
	order female_foeticide_reason_11 female_foeticide_reason_12, after(female_foeticide_reason_9)
	
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Shaadi k liye paissa na hona."
	*replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Kuch log sochate h ki SÃ bhi kam  ladke hi kr skte
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Padana nhi chahate"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladki vansh nhi chla payegi isliye"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyon ko manhush samjha jata h"
	replace female_foeticide_reason_4=1 if female_foeticide_reason_other=="Ladke k name sari property ho jaye isliye"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Pehli ladki hona paap maante hai"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladki k hone par khuwa pujan nhi kiya jata ,ladki ko dek kr raji nhi hote"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Lloyd lo pasand nai krte"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyo ko abhishap smja jata h"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladki ko pap smja jata h"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Ladki ko padhana padta hai aur uski shaadi karni padti hai"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladkiyan ghr ka vansh nahi chalati jbki ldke ghr ka vansh chalate hain"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ldkiya privar ka vansh ni chlati"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladki ko pasand nhi krna"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Kyo ki vh ladkiyo ko pyada hona asubh mante h"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladko ko ladkiyon se jyada passand karte hai"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Ladkiyo ko padhana nahi chahte"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladkiya  Vansh nahi chala pati"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladkio ko pasand nahi karte"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladle pariwar ka naam aage badatei hai"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladkiyo Pasand Nahi Kerte"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Lakiyaon ko saman nani mana jata"
	replace female_foeticide_reason_7=1 if female_foeticide_reason_other=="Janam dene wali ma ko bura bhla bolte h."
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladkiyo ko pasand nhi karte hai ."
    replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladke naam roshan karte hai  Pariwar ko kamake Khela Sakate hai"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Vansh ko aage badayega"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Ladkiyo pe kaam ni hota"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Pariwar ko a age nahi badhati"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladkiyon ke sath bedbhav Kiya jata h"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Ladki jyada paise nhi kma skti"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladki ko abishap mantey h"
	*replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Samajik boj samjha jata h or unki mansikta ka bhi frak pdta hai"
    replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladki hone k karn o aage nhi bad paygi isi karn ladki ko pet m hi maar diya jata h"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladkiyon or ladko me in bedbhav K iya jata"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyon ko apsgun mante  h"
	*replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Ladka roti dega gar walo ko"
	replace female_foeticide_reason_7=1 if female_foeticide_reason_other=="Bujurg logo ki soch"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladkiyon se parivaar nhi badta log nante h"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Pass ki kami kay karn"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Vansh veel nhi chla payegi ladki isliye"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ldkiya achi nai lgti"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyon ko apsagun mana jata hai"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="ladkiyo ko dekh kr khus nhi hote unhe apshagun mante h"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladka privar ka vansh chlata h"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Paisa kam hona"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Mats pits sochte hai ki ladkiya padh nahi sakti"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Apna vans chlane ke liye,"
	replace female_foeticide_reason_4=1 if female_foeticide_reason_other=="Jaaydad ke liye"
	replace female_foeticide_reason_2=1 if female_foeticide_reason_other=="Jyada ladki hone k karan"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ldki vansh ko aage nhi bdha skti"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladkiyo ko pasnd nhi krte"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="ladkiyo ko abhishap mana jata h ye rudiwadi darna h"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladka vansh chalayega"
	replace female_foeticide_reason_4=1 if female_foeticide_reason_other=="Ladka mata pita ka dyan rakhta hai."
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Lakdiyo ko pasand nahi karte"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Beta vansh chalayega"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Garib hone ke karan"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladki ka janam lena acha nahi mante."
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladki ko pasand na karne ki wajah se"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Lakdiya aage nahi badh sakti"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladke unka vansh aage badhayenge"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ldke vans bdhate h"
    replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladki ko pasand nahi karte."
	replace female_foeticide_reason_4=1 if female_foeticide_reason_other=="Property m hissa dena padta h"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Garibi ke karan ,samagik mahol"
	replace female_foeticide_reason_7=1 if female_foeticide_reason_other=="Ladki hone par ma ko bura bhala kaha jata hai"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyo ko apshgun mante hai."
	replace female_foeticide_reason_9=1 if female_foeticide_reason_other=="Vo sochte h ki ldkiya dukh deti h"
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Poverty"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyo ko paap mana jata h, shraap mana jata h."
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Garibi"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladko se vans badhta h."
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Bhedbhaw ki wajah se"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Vansh chalane ke liye"
	replace female_foeticide_reason_12=1 if female_foeticide_reason_other=="Ladkiyon ko badnaseeb samjhna"
	*replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Agar girl Hogi to padana padega or job karegi to money pane has bad ko degi"
	replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Unhe ladkiya achhi nhi lagti"
	replace female_foeticide_reason_11=1 if female_foeticide_reason_other=="Ladke hi vansh aage chalate h"
    replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Lakdo ko pasand karte hai."
	replace female_foeticide_reason_6=1 if female_foeticide_reason_other=="Girl Jana nahi le sake or unki padaai pe kharch na ho"
	*replace female_foeticide_reason_3=1 if female_foeticide_reason_other=="Ladko ko ladkiyon se jyada passand karte hai"
	 
	



* ===================================================================== *
* -----------------     	 TREATMENT QUESTION 		  ----------------- *
* ===================================================================== *
	
	 //br child_id issues_session* if issues_session_other!=""
	 
	 gen issues_session_8=0 if !mi(issues_session)
	 label var issues_session_8 "What are the main issues discussed during these sessions? - Save girl child and educate her"
	 
	 gen issues_session_9=0 if !mi(issues_session)
	 label var issues_session_9 "What are the main issues discussed during these sessions? - Female foeticide"
	 
	 gen issues_session_10=0 if !mi(issues_session)
	 label var issues_session_10 "What are the main issues discussed during these sessions? - Female foeticide and Save girl child and educate her" 
	 label values issues_session_8 issues_session_9 issues_session_10 issues_session

	 order issues_session_8 issues_session_9 issues_session_10, after(issues_session_6)
	 
	 replace issues_session_9=1 if issues_session_other=="About child death."
	 replace issues_session_9=1 if issues_session_other=="knya bhurn-htya"
     replace issues_session_10=1 if issues_session_other=="Education, girls child  death."
     replace issues_session_9=1 if issues_session_other=="Knya bhrun htya k bare m"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao ,sawachhata k bare m ,achhe kamo k bare m"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao"
	 replace issues_session_9=1 if issues_session_other=="About Girl child death."
	 replace issues_session_8=1 if issues_session_other=="Save girl child"
	 replace issues_session_8=1 if issues_session_other=="Ladkiyo kb uch siksa k bare m"
	 replace issues_session_9=1 if issues_session_other=="Kanya bhuran htya ke bare mani"
	 replace issues_session_10=1 if issues_session_other=="Beti bachao - beti padao k bare main or bhuran hatya k bare main"
	 replace issues_session_9=1 if issues_session_other=="Bal vivaha, kanya  bhurn hatya."
	 replace issues_session_8=1 if issues_session_other=="beti bachoo  beti padaoo"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padho"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao"
	 replace issues_session_9=1 if issues_session_other=="Kanya bhurn htya"
	 replace issues_session_10=1 if issues_session_other=="Knya brun htya   Beti bachao beti padao"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao k bare me"
	 replace issues_session_8=1 if issues_session_other=="Betiyo ko bachana chahiye,"
	 replace issues_session_9=1 if issues_session_other=="Brun htya ke bare me btate hai"
	 replace issues_session_9=1 if issues_session_other=="Kanya buran hatya"
	 replace issues_session_9=1 if issues_session_other=="Kanya burn hatya"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padhao"
	 *replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao"
	 replace issues_session_9=1 if issues_session_other=="knya-burn htya AND dhej"
	 replace issues_session_8=1 if issues_session_other=="Beti bchao beti pdao"
	 replace issues_session_8=1 if issues_session_other=="beti bachao"
	 replace issues_session_8=1 if issues_session_other=="About girl study."
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao k bare me or savchata abhiyan k bare me"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao Beti padao"
	 replace issues_session_9=1 if issues_session_other=="knya-bhurn htya"
	 replace issues_session_8=1 if issues_session_other=="Save girl"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao. ( swachta abhiyaan)"
     *replace issues_session_8=1 if issues_session_other=="Beti bachao beti padhao," // No change
	 replace issues_session_8=1 if issues_session_other=="save girl read girl"
	 replace issues_session_8=1 if issues_session_other=="Ladkiyo ki aage ki class ki padai nhi rokni chaiye ladkiyo ko uch sikha ki padai deni chaiye" 
     replace issues_session_8=1 if issues_session_other=="Save girl child, girl study."
	 replace issues_session_8=1 if issues_session_other=="Beti bachawo beti padhawo"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao k bare m"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padhao,Ladkiyo ko padhne ke liye baahar bhejna chahiye"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao or beti padao  or knya brun hatya k bare m"
	 replace issues_session_8=1 if issues_session_other=="Sawchata or bati bachao or beti padao k bare main"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao , beti padao"
	 replace issues_session_8=1 if issues_session_other=="beti bachao beti padao"
	 replace issues_session_9=1 if issues_session_other=="Kanya brun hatya or samajik samantao k baare m baat krte h"
	 replace issues_session_8=1 if issues_session_other=="Ladkiyon ko padana bachana chahi"
	 replace issues_session_8=1 if issues_session_other=="Bete bchao bete pdao"
	 replace issues_session_8=1 if issues_session_other=="beti bachao  beti padao"
	 replace issues_session_9=1 if issues_session_other=="Ladkiyo ki suraksha ke baare and bhrunn hatya ke baare mein"
	 replace issues_session_9=1 if issues_session_other=="Bhurn htya nhi honi chahiye"
	 replace issues_session_8=1 if issues_session_other=="Beti bacho beti padho"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao, acchi baate, savasthya ke bare me"
	 *replace issues_session_8=1 if issues_session_other=="Ladkiyon ko padana bachana chahi"
	 *replace issues_session_8=1 if issues_session_other=="Beti bachao beti padhao"
	 *replace issues_session_8=1 if issues_session_other=="Bete bchao bete pdao"
	 *replace issues_session_8=1 if issues_session_other=="beti bachao  beti padao"
     replace issues_session_9=1 if issues_session_other=="Ladkiyo ko bahar nahi bhejna chahiye, kanya bharun hatya nahi karni chahiye"
	 replace issues_session_8=1 if issues_session_other=="Save girls"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao or beti padao k bare m"
	 replace issues_session_9=1 if issues_session_other=="Kanya bhuran hatya ke bare manie"
	 replace issues_session_3=1 if issues_session_other=="1.Ladkiyo ko ghr se bhar jane ki anumati milni chaiye 2. Ladkiyo ko bhar pdne bhejna chaiye"
	 replace issues_session_3=1 if issues_session_other=="Molik adikaro k baare m"
	 replace issues_session_3=1 if issues_session_other=="Ladiyaon ko kamjor nahi samjhna chahiy"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao, beti padhao"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao Beti padhao, bateiyo ke surksha"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao Beti padhao"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao k bare main"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti padao  kanya bhud hatya"
	 replace issues_session_1=1 if issues_session_other=="Ladki hone par khush hona chahiye"
	 replace issues_session_8=1 if issues_session_other=="Kanya bhurn hatya, beti bachao Beti padhao, khelkud"
	 replace issues_session_8=1 if issues_session_other=="Beti bchaao beti badaao"
	 replace issues_session_8=1 if issues_session_other=="Beti bacao,beti padhao ke baare m"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti  padhao ke bare me"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao beti phdao"
	 replace issues_session_8=1 if issues_session_other=="Bete Bacho"
     replace issues_session_8=1 if issues_session_other=="Beti bachao Beti pdhao ke bare me"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao, beti padhao Rashtriya ekta"
	 replace issues_session_8=1 if issues_session_other=="Beti bcaao, beti padao" 
	 replace issues_session_8=1 if issues_session_other=="Beti bacao ,beti padao"
	 replace issues_session_8=1 if issues_session_other=="Story ,beti bachao  beti padhao"
	 replace issues_session_8=1 if issues_session_other=="Beti bachawo  beti padhawo."
	 replace issues_session_10=1 if issues_session_other=="Kanya bhruna hatya  Beti bachao beti padhao" 
	 replace issues_session_10=1 if issues_session_other=="Kanya bhud hatya  beti bchao brpeti padao"
	 replace issues_session_8=1 if issues_session_other=="Beti padho ,beti bachao"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao  beti  padhao"
	 replace issues_session_8=1 if issues_session_other=="Beti bachao Beti padhao , khelkud."
	 replace issues_session_10=1 if issues_session_other=="Kanya bhud hatya  beti bachao"
	 *replace issues_session_8=1 if issues_session_other=="Beti bacao ,beti padao" //No change
	 *replace issues_session_1=1 if issues_session_other=="Ager ladke ladkiya baraber hoge to kisi ko darr nhi lagega" //No change
	 *replace issues_session_10=1 if issues_session_other=="Beti bachao Beti padhao, kanya bhurn hatya, ling janch" // No change
